agent: DQN
alpha: 0.0
batch_size: 64
beta_0: 1.0
buffer_size: 100000
env_path: /Users/syad/Documents/code/AI/deep-reinforcement-learning/p1_navigation/Banana
eps_decay: 0.98
eps_end: 0.01
eps_start: 0.1
experiment_name: test-exp
gamma: 0.99
generate_config: false
lr: 0.0004
lr_decay: 1.0
max_t: 300
model: QNetwork
n_episodes: 300
seed: 101
tau: 0.01
update_every: 4
score_threshold: 13.0
stop_at_threshold: false 
