update_every : 4
batch_size : 64
buffer_size : 100_000
seed : 101
lr : 5.e-4
tau : 5.e-3
gamma : 0.99
# dqn or ddqn
agent : DDQN
model : DuelingQNetwork

#
n_episodes : 300
max_t : 1000

#
eps_start : 1.0
eps_end : 0.01
eps_decay : 0.995

# environment path including the name
env_path : /Users/syad/Documents/code/AI/deep-reinforcement-learning/p1_navigation/Banana

experiment_name : p1_testalpha: 0.0
alpha: 0.0
beta_0: 1.0
lr: 0.0004
lr_decay: 1.0
